name 'netkeiba'
maintainer 'hankehly'
maintainer_email 'henry.ehly@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures netkeiba'
long_description 'Installs/Configures netkeiba'
version '0.1.0'
chef_version '>= 13.0'

depends 'apt', '~> 7.1.1'
depends 'build-essential', '~> 8.2.1'
depends 'pyenv', '~> 2.0.0'
depends 'td-agent', '~> 3.0.3'
depends 'nodejs', '~> 6.0.0'
depends 'java', '~> 3.1.2'
depends 'elasticsearch', '~> 4.0.4'
depends 'kibana', '~> 0.2.3'
depends 'rsyslog', '~> 6.0.7'
