---
driver:
    name: vagrant

platforms:
    -   name: ubuntu-18.04

provisioner:
    name: chef_zero
    always_update_cookbooks: true
    data_bags_path: '../../data_bags'

suites:
    -   name: default
        run_list:
            - recipe[netkeiba]
