name 'netkeiba'
maintainer 'hankehly'
maintainer_email 'henry.ehly@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures netkeiba'
long_description 'Installs/Configures netkeiba'
version '0.1.0'
chef_version '>= 13.0'

depends 'pyenv', '~> 2.0.0'
