# Generated by Django 2.1.4 on 2018-12-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprenticeJockeyRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apprentice_jockey_races',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'course_types',
            },
        ),
        migrations.CreateModel(
            name='FemaleOnlyRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'female_only_races',
            },
        ),
        migrations.CreateModel(
            name='ForeignHorseRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'foreign_horse_races',
            },
        ),
        migrations.CreateModel(
            name='ForeignTrainerHorseRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'foreign_trainer_horse_races',
            },
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('total_races', models.PositiveSmallIntegerField()),
                ('total_wins', models.PositiveSmallIntegerField()),
                ('birthday', models.DateField()),
                ('user_rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorseSex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImpostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'impost_categories',
            },
        ),
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'jockeys',
            },
        ),
        migrations.CreateModel(
            name='NonWinnerRegionalHorseRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'non_winner_regional_horse_races',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('key', models.CharField(max_length=255, unique=True)),
                ('distance', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.CourseType')),
                ('impost_category',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.ImpostCategory')),
            ],
            options={
                'db_table': 'races',
                'get_latest_by': '-date',
            },
        ),
        migrations.CreateModel(
            name='RaceTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionalJockeyRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Race')),
            ],
            options={
                'db_table': 'regional_jockey_races',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'trainers',
            },
        ),
        migrations.CreateModel(
            name='WeatherCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'weather_categories',
            },
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(unique=True)),
                ('html', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WinnerRegionalHorseRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Race')),
            ],
            options={
                'db_table': 'winner_regional_horse_races',
            },
        ),
        migrations.AddField(
            model_name='race',
            name='racetrack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.RaceTrack'),
        ),
        migrations.AddField(
            model_name='race',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.WeatherCategory'),
        ),
        migrations.AddField(
            model_name='nonwinnerregionalhorserace',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Race'),
        ),
        migrations.AddField(
            model_name='horse',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.HorseSex'),
        ),
        migrations.AddField(
            model_name='foreigntrainerhorserace',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Race'),
        ),
        migrations.AddField(
            model_name='foreignhorserace',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Race'),
        ),
        migrations.AddField(
            model_name='femaleonlyrace',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Race'),
        ),
        migrations.AddField(
            model_name='apprenticejockeyrace',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Race'),
        ),
    ]
