# Generated by Django 2.1.4 on 2018-12-14 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='horse',
            table='horses',
        ),
        migrations.AlterModelTable(
            name='horsesex',
            table='horse_sexes',
        ),
        migrations.AlterModelTable(
            name='racetrack',
            table='racetracks',
        ),
        migrations.AlterModelTable(
            name='webpage',
            table='webpages',
        ),
    ]
