# Generated by Django 2.1.4 on 2018-12-18 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('server', '0002_auto_20181214_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetype',
            old_name='key',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='horsesex',
            old_name='key',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='impostcategory',
            old_name='key',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='weathercategory',
            old_name='key',
            new_name='name',
        ),
    ]
