# Generated by Django 2.1.5 on 2019-02-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190207_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bet_type', models.CharField(choices=[('WIN', 'Win'), ('SHOW', 'Show'), ('QUINELLA', 'Quinella'), ('BRACKET_QUINELLA', 'Bracket Quinella'), ('DUET', 'Duet'), ('EXACTA', 'Exacta'), ('TRIO ', 'Trio'), ('TRIFECTA', 'Trifecta')], max_length=255)),
                ('horse_number', models.PositiveIntegerField()),
                ('payoff', models.PositiveIntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Race')),
            ],
            options={
                'db_table': 'betting_tickets',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bettingticket',
            unique_together={('race', 'bet_type', 'horse_number')},
        ),
    ]
