# Generated by Django 2.1.4 on 2018-12-18 23:29

from django.db import migrations


def load_course_types(apps, schema_editor):
    CourseType = apps.get_model('server', 'CourseType')

    CourseType.objects.bulk_create([
        CourseType(name='turf'),
        CourseType(name='dirt'),
        CourseType(name='obstacle')
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('server', '0003_auto_20181218_2320'),
    ]

    operations = [
        migrations.RunPython(load_course_types, migrations.RunPython.noop)
    ]
