# Generated by Django 2.1.4 on 2018-12-18 23:29

from django.db import migrations


def load_racetracks(apps, schema_editor):
    RaceTrack = apps.get_model('server', 'RaceTrack')

    RaceTrack.objects.bulk_create([
        RaceTrack(name='sapporo'),
        RaceTrack(name='hakodate'),
        RaceTrack(name='fuma'),
        RaceTrack(name='niigata'),
        RaceTrack(name='tokyo'),
        RaceTrack(name='nakayama'),
        RaceTrack(name='chukyo'),
        RaceTrack(name='kyoto'),
        RaceTrack(name='hanshin'),
        RaceTrack(name='ogura'),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('server', '0004_course_types'),
    ]

    operations = [
        migrations.RunPython(load_racetracks, migrations.RunPython.noop)
    ]
