# Generated by Django 2.1.4 on 2018-12-18 23:59

from django.db import migrations


def load_weather_categories(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('server', '0006_horse_sexes'),
    ]

    operations = [
        migrations.RunPython(load_weather_categories, migrations.RunPython.noop)
    ]
