# Generated by Django 2.1.4 on 2018-12-18 23:59

from django.db import migrations


def load_impost_categories(apps, schema_editor):
    ImpostCategory = apps.get_model('server', 'ImpostCategory')

    ImpostCategory.objects.bulk_create([
        ImpostCategory(name='age_based'),
        ImpostCategory(name='age_sex_based'),
        ImpostCategory(name='decided_per_race'),
        ImpostCategory(name='handicap'),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('server', '0007_weather_categories'),
    ]

    operations = [
        migrations.RunPython(load_impost_categories, migrations.RunPython.noop)
    ]
