# Generated by Django 2.1.4 on 2018-12-18 23:59

from django.db import migrations


def load_impost_categories(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('server', '0007_weather_categories'),
    ]

    operations = [
        migrations.RunPython(load_impost_categories, migrations.RunPython.noop)
    ]
