# Generated by Django 2.1.4 on 2018-12-20 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_impost_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceContender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_of_finish', models.PositiveSmallIntegerField()),
                ('order_of_finish_lowered', models.BooleanField()),
                ('post_position', models.PositiveSmallIntegerField()),
                ('weight_carried', models.FloatField()),
                ('finish_time', models.FloatField()),
                ('first_place_odds', models.FloatField()),
                ('popularity', models.PositiveSmallIntegerField()),
                ('horse_weight', models.FloatField()),
                ('horse_weight_diff', models.FloatField()),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Horse')),
                ('jockey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Jockey')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Race')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Trainer')),
            ],
            options={
                'db_table': 'race_contenders',
            },
        ),
        migrations.AlterUniqueTogether(
            name='racecontender',
            unique_together={('race', 'horse', 'jockey', 'trainer')},
        ),
    ]
