# Generated by Django 2.1.4 on 2018-12-20 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20181220_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirtConditionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dirt_condition_categories',
            },
        ),
        migrations.CreateModel(
            name='TurfConditionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'turf_condition_categories',
            },
        ),
        migrations.AddField(
            model_name='race',
            name='dirt_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.DirtConditionCategory'),
        ),
        migrations.AddField(
            model_name='race',
            name='turf_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.TurfConditionCategory'),
        ),
    ]
