# Generated by Django 2.1.4 on 2018-12-20 23:13

from django.db import migrations


def load_track_condition_categories(apps, schema_editor):
    DirtConditionCategory = apps.get_model('server', 'DirtConditionCategory')
    TurfConditionCategory = apps.get_model('server', 'TurfConditionCategory')

    DirtConditionCategory.objects.bulk_create([
        DirtConditionCategory(name='cloudy'),
        DirtConditionCategory(name='sunny'),
        DirtConditionCategory(name='rainy'),
        DirtConditionCategory(name='snowy'),
    ])

    TurfConditionCategory.objects.bulk_create([
        TurfConditionCategory(name='cloudy'),
        TurfConditionCategory(name='sunny'),
        TurfConditionCategory(name='rainy'),
        TurfConditionCategory(name='snowy'),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('server', '0010_auto_20181220_2313'),
    ]

    operations = [
        migrations.RunPython(load_track_condition_categories, migrations.RunPython.noop)
    ]
