# Generated by Django 2.1.4 on 2018-12-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_remove_race_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.HorseSex'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='total_races',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='total_wins',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
