# Generated by Django 2.1.4 on 2018-12-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20181222_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='racecontender',
            name='did_remount',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
