# Generated by Django 2.1.4 on 2018-12-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_racecontender_did_remount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racecontender',
            name='horse_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='racecontender',
            name='horse_weight_diff',
            field=models.FloatField(null=True),
        ),
    ]
