# Generated by Django 2.1.4 on 2019-01-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20181230_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='fingerprint',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
