# Generated by Django 2.1.4 on 2019-01-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_webpage_fingerprints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='date',
        ),
        migrations.AddField(
            model_name='race',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
