SELECT
    -- race_contender
       c.id                                                        c_id,
       c.weight_carried                                            c_weight_carried,
       c.post_position                                             c_post_position,
       c.order_of_finish                                           c_order_of_finish,
       c.order_of_finish_lowered                                   c_order_of_finish_lowered,
       c.finish_time                                               c_finish_time,
       c.horse_weight                                              c_horse_weight,
       c.horse_weight_diff                                         c_horse_weight_diff,
       c.popularity                                                c_popularity,
       c.first_place_odds                                          c_first_place_odds,
    -- race
       r.id                                                        r_id,
       r.key                                                       r_key,
       (SELECT name FROM racetracks WHERE id = r.racetrack_id)     r_racetrack,
       (SELECT name FROM course_types WHERE id = r.course_type_id) r_course_type,
       r.weather                                                   r_weather,
       r.url                                                       r_url,
       r.distance                                                  r_distance,
       r.date                                                      r_date,
       r.dirt_condition                                            r_dirt_condition,
       r.turf_condition                                            r_turf_condition,
       r.impost_category                                           r_impost_category,
       r.is_non_winner_regional_horse_allowed                      r_is_non_winner_regional_horse_allowed,
       r.is_winner_regional_horse_allowed                          r_is_winner_regional_horse_allowed,
       r.is_regional_jockey_allowed                                r_is_regional_jockey_allowed,
       r.is_foreign_horse_allowed                                  r_is_foreign_horse_allowed,
       r.is_foreign_horse_and_trainer_allowed                      r_is_foreign_horse_and_trainer_allowed,
       r.is_apprentice_jockey_allowed                              r_is_apprentice_jockey_allowed,
       r.is_female_only                                            r_is_female_only,
    -- horse
       h.id                                                        h_id,
       h.key                                                       h_key,
       h.url                                                       h_url,
       h.total_races                                               h_total_races,
       h.total_wins                                                h_total_wins,
       h.sex                                                       h_sex,
       h.birthday                                                  h_birthday,
       h.user_rating                                               h_user_rating,
    -- jockey
       j.id                                                        j_id,
       j.key                                                       j_key,
       j.url                                                       j_url,
       j.career_1st_place_count                                    j_career_1st_place_count,
       j.career_2nd_place_count                                    j_career_2nd_place_count,
       j.career_3rd_place_count                                    j_career_3rd_place_count,
       j.career_4th_place_or_below_count                           j_career_4th_place_or_below_count,
       j.career_turf_race_count                                    j_career_turf_race_count,
       j.career_turf_win_count                                     j_career_turf_win_count,
       j.career_dirt_race_count                                    j_career_dirt_race_count,
       j.career_dirt_win_count                                     j_career_dirt_win_count,
       j.career_1st_place_rate                                     j_career_1st_place_rate,
       j.career_1st_2nd_place_rate                                 j_career_1st_2nd_place_rate,
       j.career_any_place_rate                                     j_career_any_place_rate,
       j.career_earnings                                           j_career_earnings,
    -- trainer
       t.id                                                        t_id,
       t.key                                                       t_key,
       t.url                                                       t_url,
       t.career_1st_place_count                                    t_career_1st_place_count,
       t.career_2nd_place_count                                    t_career_2nd_place_count,
       t.career_3rd_place_count                                    t_career_3rd_place_count,
       t.career_4th_place_or_below_count                           t_career_4th_place_or_below_count,
       t.career_turf_race_count                                    t_career_turf_race_count,
       t.career_turf_win_count                                     t_career_turf_win_count,
       t.career_dirt_race_count                                    t_career_dirt_race_count,
       t.career_dirt_win_count                                     t_career_dirt_win_count,
       t.career_1st_place_rate                                     t_career_1st_place_rate,
       t.career_1st_2nd_place_rate                                 t_career_1st_2nd_place_rate,
       t.career_any_place_rate                                     t_career_any_place_rate,
       t.career_earnings                                           t_career_earnings
FROM race_contenders c
       LEFT JOIN races r on c.race_id = r.id
       LEFT JOIN horses h on c.horse_id = h.id
       LEFT JOIN jockeys j on c.jockey_id = j.id
       LEFT JOIN trainers t on c.trainer_id = t.id
ORDER BY c_id;
